on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    # actions/setup-go: Set up your GitHub Actions workflow with a specific version of Go https://github.com/actions/setup-go/?tab=readme-ov-file
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: go test -v -shuffle on ./...
