on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # go-versions/versions-manifest.json at main · actions/go-versions https://github.com/actions/go-versions/blob/main/versions-manifest.json
        go-version: ['1.24']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    # actions/setup-go: Set up your GitHub Actions workflow with a specific version of Go https://github.com/actions/setup-go/?tab=readme-ov-file
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: go test -v -shuffle on ./...
